spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/springdesk
      username: postgres
      password: postgres
    jpa:
      show-sql: true
#      Toda vez que a aplicação for iniciada, o hibernate irá criar as tabelas no banco de dados e irá dropar as tabelas que já existem.
#      hibernate:
#        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect