spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/springdesk
      username: postgres
      password: postgres
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect